Repository UppuluriKalyani/ML-Nexus, pull requests merged in 2024-10, with the labels that each got.

#34 Added New project Plant Leaf Detection
  Neural Networks/Plant Disease Detection/README.md
  Neural Networks/Plant Disease Detection/assets/images/potato_result_graph.png
  Neural Networks/Plant Disease Detection/ipynb files/Potato_Classification.ipynb
  Neural Networks/Plant Disease Detection/ipynb files/requirements.txt
  Neural Networks/Plant Disease Detection/result.md
Labels: level2, gssoc-ext, hacktoberfest-accepted

#72 Added Human Detection Project
  Neural Networks/Human Detection Project/Dataset/Readme.md
  Neural Networks/Human Detection Project/Images/CNN_acc.png
  Neural Networks/Human Detection Project/Images/CNN_loss.png
  Neural Networks/Human Detection Project/Images/Inception.png
  Neural Networks/Human Detection Project/Images/Xception.png
  Neural Networks/Human Detection Project/Images/fine_tuned_incp.png
  Neural Networks/Human Detection Project/Images/img1.png
  Neural Networks/Human Detection Project/Images/img2.png
  Neural Networks/Human Detection Project/Images/vgg16.png
  Neural Networks/Human Detection Project/Model/Fine-tuned Human Detection Project.ipynb
  Neural Networks/Human Detection Project/Model/Human Detection Project.ipynb
  Neural Networks/Human Detection Project/Readme.md
  Neural Networks/Human Detection Project/Requirements.txt
Labels: level2, gssoc-ext, hacktoberfest-accepted

#64 Hand Game Controller using OpenCV
  Computer Vision/Hand Game Controller/README.md
  Computer Vision/Hand Game Controller/Screenshot 2024-10-03 183106.png
  Computer Vision/Hand Game Controller/Screenshot 2024-10-03 183129.png
  Computer Vision/Hand Game Controller/Screenshot 2024-10-03 183619.png
  Computer Vision/Hand Game Controller/Screenshot 2024-10-03 183644.png
  Computer Vision/Hand Game Controller/main-mobile-cam.py
  Computer Vision/Hand Game Controller/main-pc-cam.py
  Computer Vision/Hand Game Controller/requirements.txt
Labels: level2, gssoc-ext, hacktoberfest-accepted

#75 Drowsiness Detection
  Neural Networks/.DS_Store
  Neural Networks/Drowsiness detection/Drowsiness Detection(1).ipynb
  Neural Networks/Drowsiness detection/Drowsiness_README.md
Labels: level2, gssoc-ext, hacktoberfest-accepted

#84 Iris Flower Classification
  Natural Language Processing/Twitter Sentiment Analysis/README.md
  Natural Language Processing/Twitter Sentiment Analysis/Twitter Sentiment Analysis.ipynb
  Natural Language Processing/Twitter Sentiment Analysis/Twitter-sentiment-analysis-1.jpg
  Natural Language Processing/Twitter Sentiment Analysis/images.jpg
  Natural Language Processing/Twitter Sentiment Analysis/images/Input Data.jpg
  Natural Language Processing/Twitter Sentiment Analysis/images/Model Performance.jpg
  Natural Language Processing/Twitter Sentiment Analysis/images/Negative wordcloud.jpg
  Natural Language Processing/Twitter Sentiment Analysis/images/Positive wordcloud.jpg
  Natural Language Processing/Twitter Sentiment Analysis/images/Sentiment countplot.jpg
  Natural Language Processing/Twitter Sentiment Analysis/images/sample.md
  Natural Language Processing/Twitter Sentiment Analysis/train.csv
  Natural Language Processing/Twitter Sentiment Analysis/twitter2-720x540.jpg
  Neural Networks/Iris Flower Classification/2DScatter.png
  Neural Networks/Iris Flower Classification/DataVisualization.png
  Neural Networks/Iris Flower Classification/DecisionTree.png
  Neural Networks/Iris Flower Classification/Heatmap.png
  Neural Networks/Iris Flower Classification/Heatmap2.png
  Neural Networks/Iris Flower Classification/KNN.png
  Neural Networks/Iris Flower Classification/Length_Histogram.png
  Neural Networks/Iris Flower Classification/README.md
  Neural Networks/Iris Flower Classification/SVM Iris.ipynb
  Neural Networks/Iris Flower Classification/SVM.png
  Neural Networks/Iris Flower Classification/Width_Histogram.png
  Neural Networks/Iris Flower Classification/iris.ipynb
  Neural Networks/Iris Flower Classification/iris_Flower_Classification_using_KNN.ipynb
  Neural Networks/Iris Flower Classification/iris_data.csv
Labels: level1, hacktoberfest-accepted

#99 Added real time translation model (#80 Issue)
  Natural Language Processing/Translator-app/Readme.md
  Natural Language Processing/Translator-app/__pycache__/translation.cpython-311.pyc
  Natural Language Processing/Translator-app/__pycache__/utils.cpython-311.pyc
  Natural Language Processing/Translator-app/assets/styles.css
  Natural Language Processing/Translator-app/main.py
  Natural Language Processing/Translator-app/requirements.txt
  Natural Language Processing/Translator-app/translation.py
  Natural Language Processing/Translator-app/utils.py
Labels: level2, gssoc-ext, hacktoberfest-accepted

#107 Added fire detection alarm
  Computer Vision/Fire Detection Alarm/.ipynb_checkpoints/fire detection system-checkpoint.ipynb
  Computer Vision/Fire Detection Alarm/README.md
  Computer Vision/Fire Detection Alarm/fire detection system.ipynb
  Computer Vision/Fire Detection Alarm/fire-alarm.mp3
  Computer Vision/Fire Detection Alarm/fire-cascade.xml
Labels: level2, gssoc-ext, hacktoberfest-accepted

#115 Dog breed classification
  Neural Networks/Dog Species Classification/DataSet/readme.md
  Neural Networks/Dog Species Classification/Images/Input.png
  Neural Networks/Dog Species Classification/Images/dog_2.png
  Neural Networks/Dog Species Classification/Images/dog_3.png
  Neural Networks/Dog Species Classification/Images/dog_image.png
  Neural Networks/Dog Species Classification/Models/MobileNETV2.ipynb
  Neural Networks/Dog Species Classification/Models/ResNet50V2.ipynb
  Neural Networks/Dog Species Classification/Models/VGG19.ipynb
  Neural Networks/Dog Species Classification/Readme.md
Labels: level2, gssoc-ext, hacktoberfest-accepted

#125 Iris Classification using Regression
  Supervised Learning/Regression/Iris Flower Classification/README.md
  Supervised Learning/Regression/Iris Flower Classification/iris.py
  Supervised Learning/Regression/Iris Flower Classification/output/out1.png
  Supervised Learning/Regression/Iris Flower Classification/output/out2.png
  Supervised Learning/Regression/Iris Flower Classification/requirements.txt
Labels: level1, gssoc-ext, hacktoberfest-accepted

#121 Add Music Accompaniment Generator Project to ML-Nexus
  Generative Models/Music_Accompaniment_Generator/.DS_Store
  Generative Models/Music_Accompaniment_Generator/.gitattributes
  Generative Models/Music_Accompaniment_Generator/data_load.py
  Generative Models/Music_Accompaniment_Generator/midi_generate.py
  Generative Models/Music_Accompaniment_Generator/readme/MIDI Music Accompaniment Generator.md
  Generative Models/Music_Accompaniment_Generator/readme/accompaniment.png
  Generative Models/Music_Accompaniment_Generator/readme/align_1.png
  Generative Models/Music_Accompaniment_Generator/readme/align_2.png
  Generative Models/Music_Accompaniment_Generator/readme/main_melody.png
  Generative Models/Music_Accompaniment_Generator/readme/midi_music.png
  Generative Models/Music_Accompaniment_Generator/readme/structure.jpg
  Generative Models/Music_Accompaniment_Generator/readme/tokenization.jpg
  Generative Models/Music_Accompaniment_Generator/requirements.txt
  Generative Models/Music_Accompaniment_Generator/train.py
  Generative Models/Music_Accompaniment_Generator/train_model.py
  Generative Models/Music_Accompaniment_Generator/train_parameters.py
  Generative Models/Music_Accompaniment_Generator/transformer.py
  Generative Models/Music_Accompaniment_Generator/utils.py
Labels: level2, gssoc-ext, hacktoberfest-accepted

#129 implemented a cnn model for classifying traffic signs , used grstb da…
  Neural Networks/traffic_sign_recognition/ReadME.md
  Neural Networks/traffic_sign_recognition/code.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#137 Autocorrect feature
  Natural Language Processing/Autocorrect/Autocorrect.ipynb
  Natural Language Processing/Autocorrect/README.md
Labels: level2, gssoc-ext, hacktoberfest-accepted

#151 added file input and output Akashlogics1
  Natural Language Processing/webscrating and nltk score/blackcoffer article.ipynb
  Natural Language Processing/webscrating and nltk score/input/Input.xlsx
  Natural Language Processing/webscrating and nltk score/input/MasterDictionary-20241007T160032Z-001.zip
  Natural Language Processing/webscrating and nltk score/input/Objective.docx
  Natural Language Processing/webscrating and nltk score/input/Output Data Structure.xlsx
  Natural Language Processing/webscrating and nltk score/input/StopWords-20241007T160040Z-001.zip
  Natural Language Processing/webscrating and nltk score/input/Text Analysis.docx
  Natural Language Processing/webscrating and nltk score/reabme.md
  Natural Language Processing/webscrating and nltk score/result.csv
Labels: level1, gssoc-ext, hacktoberfest-accepted

#155 Sugarcane Leaf Disease Detection
  Neural Networks/Sugarcane Disease Prediction/Dataset/readme.md
  Neural Networks/Sugarcane Disease Prediction/Images/classification_report.png
  Neural Networks/Sugarcane Disease Prediction/Images/confusion_matrix.png
  Neural Networks/Sugarcane Disease Prediction/Images/input.png
  Neural Networks/Sugarcane Disease Prediction/Images/vgg16_graph.png
  Neural Networks/Sugarcane Disease Prediction/models/ensemble_model.ipynb
  Neural Networks/Sugarcane Disease Prediction/readme.md
Labels: gssoc-ext, hacktoberfest-accepted

#156 Custometrics using KMeans
  Supervised Learning/Kmeans/.ipynb_checkpoints/final (1)-checkpoint.ipynb
  Supervised Learning/Kmeans/final (1).ipynb
  Supervised Learning/Kmeans/marketing_campaign.csv
Labels: level1, gssoc-ext, hacktoberfest-accepted

#127 feat: add replay and audio download option
  Natural Language Processing/Translator-app/main.py
  Natural Language Processing/Translator-app/translation.py
Labels: level1, gssoc-ext, hacktoberfest-accepted

#173 face mask detection using computer vision added
  Computer Vision/Face Mask Detection/Dataset/Readme.md
  Computer Vision/Face Mask Detection/Images/Distribution of classes.jpg
  Computer Vision/Face Mask Detection/Images/Evaluation.jpg
  Computer Vision/Face Mask Detection/Images/Readme.md
  Computer Vision/Face Mask Detection/Images/Sample Images.jpg
  Computer Vision/Face Mask Detection/Model/Readme.md
  Computer Vision/Face Mask Detection/Model/detecting-face-masks-with-5-models.ipynb
  Computer Vision/Face Mask Detection/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted

#186 completed Issue#166 emotion and pose detection
  Computer Vision/emotion and pose dedection/program.ipynb
  Computer Vision/emotion and pose dedection/readme.md
  Computer Vision/emotion and pose dedection/sample outputs.png
  Computer Vision/object detection by colour/HSV_Results.PNG
  Computer Vision/object detection by colour/blue object.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#171 Feature Using Computer Vision to Detect Bad Posture
  Computer Vision/Bad Posture Detection MediaPipe/Media Pipe Pose checkpoint.ipynb
  Computer Vision/Bad Posture Detection MediaPipe/README.md
Labels: gssoc-ext, hacktoberfest-accepted

#175 added a animal prediction model
  Computer Vision/Deep-learning-for-Animal-Identification/Identify the Animal_colab.ipynb
  Computer Vision/Deep-learning-for-Animal-Identification/Identify_the_Animal_novalid_colab.ipynb
  Computer Vision/Deep-learning-for-Animal-Identification/README.md
  Computer Vision/Deep-learning-for-Animal-Identification/images/Image1.jpg
  Computer Vision/Deep-learning-for-Animal-Identification/images/LeaderBoard.jpg
  Computer Vision/Deep-learning-for-Animal-Identification/images/sub.jpg
  Computer Vision/Deep-learning-for-Animal-Identification/subm01.csv
Labels: gssoc-ext, hacktoberfest-accepted

#188 Created a text-to-music generator app on streamlit
  Generative Models/Text-to-Music Generator/README.md
  Generative Models/Text-to-Music Generator/app.py
  Generative Models/Text-to-Music Generator/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted

#190 Language Translator
  Natural Language Processing/Spoken Language Translator/README.MD
  Natural Language Processing/Spoken Language Translator/requirements.txt
  Natural Language Processing/Spoken Language Translator/translator.py
Labels: gssoc-ext, hacktoberfest-accepted

#195 compelted issue#165 tarffic forecast
  Time Series Analysis/Traffic Forecast in industry/Traffic Forecast - Time Series Analysis.ipynb
  Time Series Analysis/Traffic Forecast in industry/input Traffic data.csv
  Time Series Analysis/Traffic Forecast in industry/readme.md
Labels: gssoc-ext, hacktoberfest-accepted

#196 Stock Prediction with CAPM and Fama-French Model
  Prediction Models/stock_prediction/CAPM_FamaFrench.ipynb
  Prediction Models/stock_prediction/README.md
  Prediction Models/stock_prediction/output_1.png
  Prediction Models/stock_prediction/output_10.png
  Prediction Models/stock_prediction/output_11.png
  Prediction Models/stock_prediction/output_12.png
  Prediction Models/stock_prediction/output_2.png
  Prediction Models/stock_prediction/output_3.png
  Prediction Models/stock_prediction/output_4.png
  Prediction Models/stock_prediction/output_5.png
  Prediction Models/stock_prediction/output_6.png
  Prediction Models/stock_prediction/output_7.png
  Prediction Models/stock_prediction/output_8.png
  Prediction Models/stock_prediction/output_9.png
Labels: gssoc-ext, hacktoberfest-accepted

#200 Added ChatDocs AI: An AI chatbot for PDF interactions
  Generative Models/ChatDocs-AI/README.md
  Generative Models/ChatDocs-AI/chat_handler.py
  Generative Models/ChatDocs-AI/config.py
  Generative Models/ChatDocs-AI/main.py
  Generative Models/ChatDocs-AI/pdf_processing.py
  Generative Models/ChatDocs-AI/requirements.txt
  Generative Models/ChatDocs-AI/util.py
Labels: level2, gssoc-ext, hacktoberfest-accepted

#202 Issue#197
  web scraping in python/quotes.toscrape.com/output.xlsx
  web scraping in python/quotes.toscrape.com/readme.md
  web scraping in python/quotes.toscrape.com/scrap.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#204 Bitcoin Price Prediction Using LSTM In Prediction Models
  Prediction Models/Bitcoin Price Prediction Using Lstm/.ipynb_checkpoints/Bitcoin Price Prediction LSTM-checkpoint.ipynb
  Prediction Models/Bitcoin Price Prediction Using Lstm/BTC-USD.csv
  Prediction Models/Bitcoin Price Prediction Using Lstm/Bitcoin Price Prediction LSTM.ipynb
  Prediction Models/Bitcoin Price Prediction Using Lstm/README.md
Labels: gssoc-ext, hacktoberfest-accepted

#218 Delete Transfer Learning/s.txt
  Transfer Learning/s.txt
Labels: gssoc-ext, hacktoberfest-accepted

#219 Added brain tumor detection
  Computer Vision/Brain-Tumor-Detection/Brain_tumor_predict.ipynb
  Computer Vision/Brain-Tumor-Detection/README.md
  Computer Vision/Brain-Tumor-Detection/app.py
  Computer Vision/Brain-Tumor-Detection/img/1.PNG
  Computer Vision/Brain-Tumor-Detection/static/css/main.css
  Computer Vision/Brain-Tumor-Detection/static/js/main.js
  Computer Vision/Brain-Tumor-Detection/templates/base.html
  Computer Vision/Brain-Tumor-Detection/templates/index.html
  Computer Vision/Brain-Tumor-Detection/uploads/1.jpg
Labels: level2, gssoc-ext, hacktoberfest-accepted

#221 Added indian election prediction
  Computer Vision/india-elections2024/LICENSE
  Computer Vision/india-elections2024/README.md
  Computer Vision/india-elections2024/election2024.html
  Computer Vision/india-elections2024/india_pc_2024_simplified.geojson
  Computer Vision/india-elections2024/map-create.ipynb
  Computer Vision/india-elections2024/screenshot.png
Labels: gssoc-ext, hacktoberfest-accepted

#222 anomalyPrediction with mask
  Computer Vision/anomalyPrediction with mask/README.md
  Computer Vision/anomalyPrediction with mask/anomalyprediction-with-mask.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#224 Bird Species Identification using Deep Learning Streamlit #180
  Computer Vision/ Bird Species Identification/Bird_Classification.py
  Computer Vision/ Bird Species Identification/README.md
  Computer Vision/ Bird Species Identification/birds-classification-using-tflearning.ipynb
  Computer Vision/ Bird Species Identification/meta/logo.jpg
  Computer Vision/ Bird Species Identification/meta/logo1.png
  Computer Vision/ Bird Species Identification/requirements.txt
  Computer Vision/ Bird Species Identification/test.py
  Computer Vision/ Bird Species Identification/uploaded_images/1.jpg
  Computer Vision/ Bird Species Identification/uploaded_images/3.jpg
  Computer Vision/ Bird Species Identification/uploaded_images/4.jpg
  Computer Vision/ Bird Species Identification/uploaded_images/5.jpg
Labels: level2, gssoc-ext, hacktoberfest-accepted

#225 Intrusion Detection System Using Apriori and Association Rule Mining
  Unsupervised Learning/Intrusion Detection System/Dataset/Test_data.csv
  Unsupervised Learning/Intrusion Detection System/Dataset/Train_data.csv
  Unsupervised Learning/Intrusion Detection System/Image/output.png
  Unsupervised Learning/Intrusion Detection System/network-intrusion-detection-using-ARM.ipynb
  Unsupervised Learning/Intrusion Detection System/readme.md
Labels: level2, gssoc-ext, hacktoberfest-accepted

#234 Prediction of medical expenses of a Insurance holding person
  Prediction Models/Medical_Cost_of_Insurance_Person/Medical_cost_of_insurance_person.ipynb
  Prediction Models/Medical_Cost_of_Insurance_Person/app.py
  Prediction Models/Medical_Cost_of_Insurance_Person/insurance.csv
Labels: level1, gssoc-ext, hacktoberfest-accepted

#238 Feature request: Landmark detection web app
  Computer Vision/Landmark Detection/app.py
  Computer Vision/Landmark Detection/images/image1.jpeg
  Computer Vision/Landmark Detection/images/image2.jpeg
  Computer Vision/Landmark Detection/images/image3.jpeg
  Computer Vision/Landmark Detection/images/image4.jpeg
  Computer Vision/Landmark Detection/images/image5.jpeg
  Computer Vision/Landmark Detection/landmark-detection-tfhub.ipynb
  Computer Vision/Landmark Detection/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted

#239 Car PricePrediction
  Prediction Models/Car_Price_Prediction/Car_price_prediction.ipynb
  Prediction Models/Car_Price_Prediction/app.py
  Prediction Models/Car_Price_Prediction/car data.csv
Labels: gssoc-ext, hacktoberfest-accepted

#243 Added Children vs Adults Classification using DL
  Neural Networks/Children vs Adults Classification using DL/Models/Children vs Adult Classification.ipynb
  Neural Networks/Children vs Adults Classification using DL/Models/m
  Neural Networks/Children vs Adults Classification using DL/README.md
Labels: gssoc-ext, hacktoberfest-accepted

#244 Medical Diagnoser
  Neural Networks/Medical_diagnoser/Dataset/medical_data.csv
  Neural Networks/Medical_diagnoser/Readme.md
  Neural Networks/Medical_diagnoser/medical.ipynb
  Neural Networks/Medical_diagnoser/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted

#250 Anomaly-Based Intrusion Detection System
  Neural Networks/Anomaly_based_ids/Anomaly_based_IDS.ipynb
  Neural Networks/Anomaly_based_ids/README.md
  Neural Networks/Anomaly_based_ids/saved_model/IDS_model_20241010-184208.h5
Labels: gssoc-ext, hacktoberfest-accepted

#258 Style Transfer with Neural Networks
  Transfer Learning/Style Transfer with Neural Networks/README.md
  Transfer Learning/Style Transfer with Neural Networks/Style Transfer with Neural Networks.ipynb
  Transfer Learning/Style Transfer with Neural Networks/content image.jpg
  Transfer Learning/Style Transfer with Neural Networks/style image.jpg
Labels: gssoc-ext, hacktoberfest-accepted

#265 Breast Cancer Classification Added
  Supervised Learning/Bayesian Classifier/Breast Cancer Classification/Dataset/breast-cancer.csv
  Supervised Learning/Bayesian Classifier/Breast Cancer Classification/README.md
  Supervised Learning/Bayesian Classifier/Breast Cancer Classification/RESULT.md
  Supervised Learning/Bayesian Classifier/Breast Cancer Classification/asset/images/1.png
  Supervised Learning/Bayesian Classifier/Breast Cancer Classification/asset/images/2.png
  Supervised Learning/Bayesian Classifier/Breast Cancer Classification/asset/images/3.png
  Supervised Learning/Bayesian Classifier/Breast Cancer Classification/breast_cancer_prediction.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#267 Blur Detection Using Laplacian (CV2) | Python
  Computer Vision/Blur Detection/README.md
  Computer Vision/Blur Detection/blur_detection.py
Labels: gssoc-ext, hacktoberfest-accepted

#281 Airbnb Price Prediction Added In Prediction Models
  Prediction Models/Airbnb Price Prediction/Dataset/README.md
  Prediction Models/Airbnb Price Prediction/Model/.ipynb_checkpoints/Airbnb_Price_Prediction-checkpoint.ipynb
  Prediction Models/Airbnb Price Prediction/Model/Airbnb_Price_Prediction.ipynb
  Prediction Models/Airbnb Price Prediction/Model/README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#286 image to text generative model completed
  Generative Models/image-to-text model/model.py
  Generative Models/image-to-text model/model_Readme.md
  Generative Models/image-to-text model/results.jpg
Labels: gssoc-ext, hacktoberfest-accepted

#287 completed implementation of classfiction model which will detect pote…
  Supervised Learning/suicide-detection/ReadMe.md
  Supervised Learning/suicide-detection/main.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#289 Predict Employee Turnover
  Prediction Models/Predict Employee Turnover with scikitlearn/Learner_Notebook3.ipynb
  Prediction Models/Predict Employee Turnover with scikitlearn/README.md
  Prediction Models/Predict Employee Turnover with scikitlearn/employee_data.csv
  Prediction Models/Predict Employee Turnover with scikitlearn/partition-feature-space.png
Labels: level1, gssoc-ext, hacktoberfest-accepted

#290 Linear regression model
  Prediction Models/Exam Score Prediction/Applying Linear Regression Model to Predict Exam Score.ipynb
  Prediction Models/Exam Score Prediction/README.md
  Prediction Models/Exam Score Prediction/student_exam_data_new.csv
Labels: gssoc-ext, hacktoberfest-accepted

#291 Animate me Added in computer vision dir
  Computer Vision/Animate Me!/.ipynb_checkpoints/animate_me-checkpoint.ipynb
  Computer Vision/Animate Me!/Input Image/Amy.jpg
  Computer Vision/Animate Me!/Output Image/AmyOP.jpeg
  Computer Vision/Animate Me!/README.md
  Computer Vision/Animate Me!/animate_me.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#293 added all project files
  Prediction Models/Credit Card Fraud Detection/README.md
  Prediction Models/Credit Card Fraud Detection/fraud.ipynb
  Prediction Models/Credit Card Fraud Detection/requirements.txt
Labels: level1, gssoc-ext, hacktoberfest-accepted

#296 Abstractive Text Summarization Transformer Model added in Natural Lan…
  Natural Language Processing/Abstractive Text Summarization Transformer Model - NLP/.ipynb_checkpoints/Abstractive_Text_Summarization_Transformer_Model-checkpoint.ipynb
  Natural Language Processing/Abstractive Text Summarization Transformer Model - NLP/Abstractive_Text_Summarization_Transformer_Model.ipynb
  Natural Language Processing/Abstractive Text Summarization Transformer Model - NLP/README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#297 Housing Price Prediction
  Prediction Models/Housing_Price_Prediction/Housing_price.ipynb
  Prediction Models/Housing_Price_Prediction/app.py
  Prediction Models/Housing_Price_Prediction/test.csv
  Prediction Models/Housing_Price_Prediction/train.csv
Labels: level1, gssoc-ext, hacktoberfest-accepted

#301 Feature request: SQL query assistant
  Generative Models/AI-Query-editor/README.md
  Generative Models/AI-Query-editor/app.py
  Generative Models/AI-Query-editor/requirements.txt
Labels: level1, gssoc-ext, hacktoberfest-accepted

#302 College Admission prediction
  Prediction Models/Getting Admission in College Prediction/Admission prediction.ipynb
  Prediction Models/Getting Admission in College Prediction/Readme.md
  Prediction Models/Getting Admission in College Prediction/admission_predict.csv
Labels: level1, gssoc-ext, hacktoberfest-accepted

#303 Adding Paddy Disease Prediction Model using Dl
  Neural Networks/Paddy Disease classification/Dataset/readme.md
  Neural Networks/Paddy Disease classification/Image/output.png
  Neural Networks/Paddy Disease classification/model/paddy-disease-classification.ipynb
  Neural Networks/Paddy Disease classification/model/rice_model.h5
  Unsupervised Learning/Intrusion Detection System/Train_data.csv
Labels: level1, gssoc-ext, hacktoberfest-accepted

#310 Rock-Paper-Scissors Game Implementation using OpenCV Hand Tracking
  Computer Vision/Rock-Paper-Scissor-Game/1.png
  Computer Vision/Rock-Paper-Scissor-Game/2.png
  Computer Vision/Rock-Paper-Scissor-Game/3.png
  Computer Vision/Rock-Paper-Scissor-Game/BG.png
  Computer Vision/Rock-Paper-Scissor-Game/main.py
  Computer Vision/Rock-Paper-Scissor-Game/readme.md
  Computer Vision/Rock-Paper-Scissor-Game/requirements.txt
Labels: level3, gssoc-ext, hacktoberfest-accepted

#312 Autoencoder - Deep CNN added in Neural Networks
  Neural Networks/Autoencoder - Deep CNN/.ipynb_checkpoints/Deep CNN Autoencoder - Denoising Image-checkpoint.ipynb
  Neural Networks/Autoencoder - Deep CNN/.ipynb_checkpoints/Deep CNN Autoencoder - Image Compression-checkpoint.ipynb
  Neural Networks/Autoencoder - Deep CNN/Deep CNN Autoencoder - Denoising Image.ipynb
  Neural Networks/Autoencoder - Deep CNN/README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#314 Voice Gender Identification added in Prediction Models
  Prediction Models/Voice Gender Identification/Dataset/README.md
  Prediction Models/Voice Gender Identification/Dataset/voice.csv
  Prediction Models/Voice Gender Identification/Model/.ipynb_checkpoints/Voice_Gender_Identification-checkpoint.ipynb
  Prediction Models/Voice Gender Identification/Model/README.md
  Prediction Models/Voice Gender Identification/Model/Voice_Gender_Identification.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#318 Added Optical Character Recognition project (opencv)
  Computer Vision/Optical Character Recognition/README.md
  Computer Vision/Optical Character Recognition/ocr.ipynb
  Computer Vision/Optical Character Recognition/results/testocr.png
  Computer Vision/Optical Character Recognition/results/testocr.txt.txt
Labels: gssoc-ext, hacktoberfest-accepted

#324 Feature request - Hybrid Recommendation System for Model Selection
  Recommendation Systems/Hybrid-recommendation-system/Hybrid-recommendations.py
  Recommendation Systems/Hybrid-recommendation-system/collaborative-filtering.py
  Recommendation Systems/Hybrid-recommendation-system/content-based-filtering.py
  Recommendation Systems/Hybrid-recommendation-system/readme.md
Labels: gssoc-ext, hacktoberfest-accepted

#342 Spam detection model
  Prediction Models/Spam Detector/.ipynb_checkpoints/Spam_detector_model-checkpoint.ipynb
  Prediction Models/Spam Detector/.ipynb_checkpoints/Untitled-checkpoint.ipynb
  Prediction Models/Spam Detector/Readme.md
  Prediction Models/Spam Detector/Spam_detector_model.ipynb
  Prediction Models/Spam Detector/Task_1.csv
Labels: gssoc-ext, hacktoberfest-accepted

#347 heart disease prediction using machine learning
  Prediction Models/Heart-Disease-Prediction-using-Machine-Learning/Heart_disease_prediction.ipynb
  Prediction Models/Heart-Disease-Prediction-using-Machine-Learning/README.md
  Prediction Models/Heart-Disease-Prediction-using-Machine-Learning/heart.csv
Labels: gssoc-ext, hacktoberfest-accepted

#350 gesture controlled snake game using opencv added
  Computer Vision/Gesture-Controlled-Snake-Game/.gitignore
  Computer Vision/Gesture-Controlled-Snake-Game/LICENSE
  Computer Vision/Gesture-Controlled-Snake-Game/README.md
  Computer Vision/Gesture-Controlled-Snake-Game/SnakeGame.py
  Computer Vision/Gesture-Controlled-Snake-Game/game-control-using-object-tracking-multithreaded.py
  Computer Vision/Gesture-Controlled-Snake-Game/game-control-using-object-tracking.py
  Computer Vision/Gesture-Controlled-Snake-Game/images/Game-Play.png
  Computer Vision/Gesture-Controlled-Snake-Game/images/SnakeGameWelcomeScreen.png
  Computer Vision/Gesture-Controlled-Snake-Game/object-detection.py
  Computer Vision/Gesture-Controlled-Snake-Game/object-tracking-direction-detection.py
  Computer Vision/Gesture-Controlled-Snake-Game/requirements.txt
  Computer Vision/Gesture-Controlled-Snake-Game/settingsSnakeFun.py
  Computer Vision/Gesture-Controlled-Snake-Game/sounds/appleEatSound.wav
  Computer Vision/Gesture-Controlled-Snake-Game/sounds/bgmusic.mid
Labels: gssoc-ext, hacktoberfest-accepted

#354 Added hand gesture recognition project
  Computer Vision/Hand Gesture Recongnition/README.md
  Computer Vision/Hand Gesture Recongnition/hand_gesture.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#355 Added food classification
  Computer Vision/Food Classification/README.md
  Computer Vision/Food Classification/food_classification.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#360 Image Caption Generator - Flickr Dataset Added in Generative Models
  Generative Models/Image Caption Generator - Flickr Dataset/.ipynb_checkpoints/Image Caption Generator CNN-LSTM-checkpoint.ipynb
  Generative Models/Image Caption Generator - Flickr Dataset/Image Caption Generator CNN-LSTM.ipynb
  Generative Models/Image Caption Generator - Flickr Dataset/README.md
Labels: gssoc-ext, hacktoberfest-accepted

#359 Added file for 3d pose estimation
  Computer Vision/3d_pose_estimation/3d_pose_estimation.py
  Computer Vision/3d_pose_estimation/Result.mp4
  Computer Vision/3d_pose_estimation/readme.md
Labels: level2, gssoc-ext, hacktoberfest-accepted

#367 Chatbot to learn GenAI
  Generative Models/Chatbot-learn-GenAI/README.md
  Generative Models/Chatbot-learn-GenAI/app.py
Labels: level1, gssoc-ext, hacktoberfest-accepted

#382 Added Time_series_analysis for Human Migration
  Time Series Analysis/Human_Migration/README.md
  Time Series Analysis/Human_Migration/migration_nz.csv
  Time Series Analysis/Human_Migration/models/gradient_boosting_model.pkl
  Time Series Analysis/Human_Migration/models/random_forest_model.pkl
  Time Series Analysis/Human_Migration/models/scaler.pkl
  Time Series Analysis/Human_Migration/models/xgboost_model.pkl
  Time Series Analysis/Human_Migration/test.py
  Time Series Analysis/Human_Migration/time_series_analysis.ipynb
Labels: level2, gssoc-ext, hacktoberfest-accepted

#383 Added ML libraries overview
  ML_LIBRARIES.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted

#391 LinkedIn Job Extractor - Job data extraction tool from the web using Scrapy #375
  web scraping in python/jobs.linkedin.com/linkedin_scraper/README.md
  web scraping in python/jobs.linkedin.com/linkedin_scraper/linkedin_scraper/__init__.py
  web scraping in python/jobs.linkedin.com/linkedin_scraper/linkedin_scraper/__pycache__/__init__.cpython-311.pyc
  web scraping in python/jobs.linkedin.com/linkedin_scraper/linkedin_scraper/__pycache__/settings.cpython-311.pyc
  web scraping in python/jobs.linkedin.com/linkedin_scraper/linkedin_scraper/items.py
  web scraping in python/jobs.linkedin.com/linkedin_scraper/linkedin_scraper/jobsdata1.json
  web scraping in python/jobs.linkedin.com/linkedin_scraper/linkedin_scraper/middlewares.py
  web scraping in python/jobs.linkedin.com/linkedin_scraper/linkedin_scraper/pipelines.py
  web scraping in python/jobs.linkedin.com/linkedin_scraper/linkedin_scraper/settings.py
  web scraping in python/jobs.linkedin.com/linkedin_scraper/linkedin_scraper/spiders/__init__.py
  web scraping in python/jobs.linkedin.com/linkedin_scraper/linkedin_scraper/spiders/__pycache__/__init__.cpython-311.pyc
  web scraping in python/jobs.linkedin.com/linkedin_scraper/linkedin_scraper/spiders/__pycache__/jobs.cpython-311.pyc
  web scraping in python/jobs.linkedin.com/linkedin_scraper/linkedin_scraper/spiders/jobs.py
  web scraping in python/jobs.linkedin.com/linkedin_scraper/scrapy.cfg
Labels: level2, gssoc-ext, hacktoberfest-accepted

#393 OMR Scanner with OpenCV and Streamlit
  Computer Vision/OMR_test_grader/README.md
  Computer Vision/OMR_test_grader/Results/output.jpg
  Computer Vision/OMR_test_grader/Results/output2.jpg
  Computer Vision/OMR_test_grader/app.py
  Computer Vision/OMR_test_grader/omr.ipynb
  Computer Vision/OMR_test_grader/requirements.txt
Labels: level2, gssoc-ext, hacktoberfest-accepted

#394 Weapon Detection System
  Computer Vision/WEAPON-DETECTION-SYSTEM/.gitattributes
  Computer Vision/WEAPON-DETECTION-SYSTEM/README.md
  Computer Vision/WEAPON-DETECTION-SYSTEM/req.txt
  Computer Vision/WEAPON-DETECTION-SYSTEM/weapon_detection.py
  Computer Vision/WEAPON-DETECTION-SYSTEM/weapon_detection1.py
  Computer Vision/WEAPON-DETECTION-SYSTEM/yolov3_testing.cfg
Labels: gssoc-ext, hacktoberfest-accepted

#400 Add text-to-speech model
  Generative Models/text-to-speech model/model.py
  Generative Models/text-to-speech model/model_readme.md
  Generative Models/text-to-speech model/requirements.txt
Labels: level2, gssoc-ext, hacktoberfest-accepted

#403 GithubTopicMiner:GitHub Repository Topics Extraction Using BeautifulSoup and NLP
  web scraping in python/repo.github.com/github_repo_scraper/README.md
  web scraping in python/repo.github.com/github_repo_scraper/github_repo_scraper.ipynb
Labels: level2, gssoc-ext, hacktoberfest-accepted

#415 Fixed Output images in Predicting Multivitamine Purchase
  Prediction Models/Predicting Multivitaimne Purchase/Readme.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#405 AI-Powered Resume Analyzer with LLM #399
  Generative Models/AI-RESUME-ANALYZER/AI_Powered_Resume_Analyzer.ipynb
  Generative Models/AI-RESUME-ANALYZER/AI_Powered_Resume_Analyzer_with_gemini.ipynb
  Generative Models/AI-RESUME-ANALYZER/README.md
Labels: level2, gssoc-ext, hacktoberfest-accepted

#417 Added Models to predict Birth Rate
  Time Series Analysis/Birth_rate_Forecasting/README.md
  Time Series Analysis/Birth_rate_Forecasting/daily-total-births.csv
  Time Series Analysis/Birth_rate_Forecasting/models/arima_model.pkl
  Time Series Analysis/Birth_rate_Forecasting/models/lstm_model.h5
  Time Series Analysis/Birth_rate_Forecasting/models/prophet_model.pkl
  Time Series Analysis/Birth_rate_Forecasting/models/scaler.pkl
  Time Series Analysis/Birth_rate_Forecasting/models_training.ipynb
  Time Series Analysis/Birth_rate_Forecasting/test.py
Labels: level2, gssoc-ext, hacktoberfest-accepted

#420 Added Documentations
  Computer Vision/Readme.md
  Generative Models/Readme.md
  Natural Language Processing/Readme.md
  Neural Networks/Readme.md
  Supervised Learning/Readme.md
  Transfer Learning/Readme.md
  Unsupervised Learning/Readme.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#426 Feature/pirate-filter
  Computer Vision/Face-Filters/Pirate-Filter/Code.py
  Computer Vision/Face-Filters/Pirate-Filter/Images/Image.jpg
  Computer Vision/Face-Filters/Pirate-Filter/Images/hat.png
  Computer Vision/Face-Filters/Pirate-Filter/Images/moustache.png
  Computer Vision/Face-Filters/Pirate-Filter/Images/output.jpg
  Computer Vision/Face-Filters/Pirate-Filter/Images/output2.png
  Computer Vision/Face-Filters/Pirate-Filter/Images/pipeline.png
  Computer Vision/Face-Filters/Pirate-Filter/Images/pirate filtered image.png
  Computer Vision/Face-Filters/Pirate-Filter/Images/pirates.png
  Computer Vision/Face-Filters/Pirate-Filter/Images/plot.png
  Computer Vision/Face-Filters/Pirate-Filter/Readme.MD
Labels: level2, gssoc-ext, hacktoberfest-accepted

#424 Dog_Vs_cat CLassification added
  Transfer Learning/Dog_Vs_Cat_Classification/Cat_test.jpg
  Transfer Learning/Dog_Vs_Cat_Classification/Dog_test.jpg
  Transfer Learning/Dog_Vs_Cat_Classification/Dog_vs_Cat_Classification_Transfer_Learning.ipynb
  Transfer Learning/Dog_Vs_Cat_Classification/README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#432 Flower Glasses filter added
  Computer Vision/Face-Filters/FlowerGlasses-Filter/Dataset/frontalEyes35x16.xml
  Computer Vision/Face-Filters/FlowerGlasses-Filter/Dataset/haarcascade_frontalface_alt.xml
  Computer Vision/Face-Filters/FlowerGlasses-Filter/Glasses.py
  Computer Vision/Face-Filters/FlowerGlasses-Filter/Readme.md
  Computer Vision/Face-Filters/FlowerGlasses-Filter/abcd.jpg
  Computer Vision/Face-Filters/FlowerGlasses-Filter/glasses.png
Labels: level1, gssoc-ext, hacktoberfest-accepted

#436 Create auto_assign_for_pr.yml
  .github/workflows/auto_assign_for_pr.yml
Labels: gssoc-ext, hacktoberfest-accepted

#443 Flight fare prediction
  Prediction Models/Flight_Fare_Prediction/Flight_Fare_Prediction
  Prediction Models/Flight_Fare_Prediction/README.md
  Prediction Models/Flight_Fare_Prediction/ffp1.png
  Prediction Models/Flight_Fare_Prediction/ffp2.png
  Prediction Models/Flight_Fare_Prediction/ffp3.png
  Prediction Models/Flight_Fare_Prediction/ffp4.png
  Prediction Models/Flight_Fare_Prediction/flight_price (1).ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#444 Contribute: Vehicles Classification using CNN
  Neural Networks/Vehicle Classifier/README.md
  Neural Networks/Vehicle Classifier/app.py
  Neural Networks/Vehicle Classifier/requirements.txt
  Neural Networks/Vehicle Classifier/static/css/styles.css
  Neural Networks/Vehicle Classifier/templates/app.html
  Neural Networks/Vehicle Classifier/vehicle_recognizer.ipynb
Labels: level2, gssoc-ext, hacktoberfest-accepted

#445 Added roadmap to learn generative AI
  GENERATIVE_AI_ROADMAP.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted

#446 fruit classification
  Computer Vision/Fruit Classification Model/Output.png
  Computer Vision/Fruit Classification Model/README.md
  Computer Vision/Fruit Classification Model/fruit-image-classification.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#449 Add sentiment analysis project
  Natural Language Processing/Sentiment Analysis Of Restaurant Reviews/readme.md
  Natural Language Processing/Sentiment Analysis Of Restaurant Reviews/sentiment-analysis.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#450 Automated NLP Text Summarization tool using spaCy
  Natural Language Processing/Abstractive Text Summarization Transformer Model - NLP/Automated Text Summarization tool/Auto_Text_Summarization_using spaCy
  Natural Language Processing/Abstractive Text Summarization Transformer Model - NLP/Automated Text Summarization tool/Automated Text Summarization.ipynb
  Natural Language Processing/Abstractive Text Summarization Transformer Model - NLP/Automated Text Summarization tool/README (3).md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#452 Restaurant Recommendation System
  Recommendation Systems/restaurant_recommendation/README.md
  Recommendation Systems/restaurant_recommendation/Restaurant_Recommendation.ipynb
  Recommendation Systems/restaurant_recommendation/restaurants.csv
Labels: level1, gssoc-ext, hacktoberfest-accepted

#453 Delete .github/workflows/auto_assign_for_pr.yml
  .github/workflows/auto_assign_for_pr.yml
Labels: hacktoberfest-accepted, hacktoberfest

#464 Added Multimodal VQA using BLIP & CLIP model
  Generative Models/Multimodal VQA using BLIP model (Visual Question and answer generative model using image prompts)/Mutimodal VQA.(using CLIP and VizWiz dataset).ipynb
  Generative Models/Multimodal VQA using BLIP model (Visual Question and answer generative model using image prompts)/README (12).md
  Generative Models/Multimodal VQA using BLIP model (Visual Question and answer generative model using image prompts)/VQA Model using BLIP
  Generative Models/Multimodal VQA using BLIP model (Visual Question and answer generative model using image prompts)/VQA_image_processing(Using_BLIP).ipynb
  Generative Models/Multimodal VQA using BLIP model (Visual Question and answer generative model using image prompts)/qna-1-demo.png
  Generative Models/Multimodal VQA using BLIP model (Visual Question and answer generative model using image prompts)/requirements.txt
  Generative Models/Multimodal VQA using BLIP model (Visual Question and answer generative model using image prompts)/src/src files
  Generative Models/Multimodal VQA using BLIP model (Visual Question and answer generative model using image prompts)/src/test_img2.png
  Generative Models/Multimodal VQA using BLIP model (Visual Question and answer generative model using image prompts)/src/test_img3.png
  Generative Models/Multimodal VQA using BLIP model (Visual Question and answer generative model using image prompts)/src/test_img4.png
  Generative Models/Multimodal VQA using BLIP model (Visual Question and answer generative model using image prompts)/src/test_img_ronaldo.jpg
Labels: level3, gssoc-ext, hacktoberfest-accepted

#465 Added reinforcement learning and drone detection files
  Reinforcement Learning/Drone Detection/Navigating Drone Detection using Reinforcement Learning techniques
  Reinforcement Learning/Drone Detection/README (10).md
  Reinforcement Learning/Drone Detection/drone_navigator.ipynb
  Reinforcement Learning/Drone Detection/gitignore.txt
  Reinforcement Learning/Drone Detection/requirements.txt
Labels: level1, gssoc-ext, hacktoberfest-accepted

#466 Contour Detection
  Computer Vision/Contour Detection in an Image/Images/Input.jpg
  Computer Vision/Contour Detection in an Image/Images/Output.png
  Computer Vision/Contour Detection in an Image/Readme.md
  Computer Vision/Contour Detection in an Image/main.py
Labels: level1, gssoc-ext, hacktoberfest-accepted

#456 Virtual Try-On System (VITON) for Clothes
  Generative Models/Virtual Try-On System (VITON) for Clothes/Coarse Image Generation.ipynb
  Generative Models/Virtual Try-On System (VITON) for Clothes/data/clothing_images/clothing1.png
  Generative Models/Virtual Try-On System (VITON) for Clothes/data/user_images/user1.png
  Generative Models/Virtual Try-On System (VITON) for Clothes/output/Screenshot 2024-10-18 202742.png
  Generative Models/Virtual Try-On System (VITON) for Clothes/readme.md
Labels: level2, gssoc-ext, hacktoberfest-accepted

#473 Added Malady Detection
  Transfer Learning/Malady_Detection_Using_X_Ray/Readme.md
  Transfer Learning/Malady_Detection_Using_X_Ray/resnet-18.ipynb
  Transfer Learning/Malady_Detection_Using_X_Ray/vgg16.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#477 Update README.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted

#486 Eye-Controlled Mouse using Eye Tracking
  Computer Vision/Mouse Control using Eye Tracking/main.py
  Computer Vision/Mouse Control using Eye Tracking/readme.md
  Computer Vision/Mouse Control using Eye Tracking/requirements.txt
Labels: level2, gssoc-ext, hacktoberfest-accepted

#487 Crater Detection Model for Lunar Surface
  Computer Vision/Crater Detection/Crater_detection.ipynb
  Computer Vision/Crater Detection/Readme.md
  Computer Vision/Crater Detection/images/input_sample.jpg
  Computer Vision/Crater Detection/images/output_sample.jpeg
Labels: level1, gssoc-ext, hacktoberfest-accepted

#490 Feature Add: Deep Learning models for fraud transaction
  Neural Networks/Fraud Transaction Predictive NN/Models/ANN SMOTE Sampling.ipynb
  Neural Networks/Fraud Transaction Predictive NN/Models/Anamoly_detection_Model_Interpretation.ipynb
  Neural Networks/Fraud Transaction Predictive NN/Models/CNN Predictive model.ipynb
  Neural Networks/Fraud Transaction Predictive NN/Models/MLP Neural Network Model.ipynb
  Neural Networks/Fraud Transaction Predictive NN/README.md
  Neural Networks/Fraud Transaction Predictive NN/neural_networks/ANN_model.h5
  Neural Networks/Fraud Transaction Predictive NN/neural_networks/CNN_model.h5
  Neural Networks/Fraud Transaction Predictive NN/neural_networks/MLP_model.h5
  Neural Networks/Fraud Transaction Predictive NN/requirements.txt
Labels: level1, gssoc-ext, hacktoberfest-accepted

#493 Fix issue 485: - Generate ML model data through video
  Computer Vision/Generate ML model with video/main.ipynb
  Computer Vision/Generate ML model with video/readme.md
Labels: level2, gssoc-ext, hacktoberfest-accepted

#497 Changes
  Time Series Analysis/LSTM_Bot/LSTM.py
  Time Series Analysis/LSTM_Bot/bot.py
  Time Series Analysis/LSTM_Bot/data/AAPL_data.csv
  Time Series Analysis/LSTM_Bot/data/test_predictions.csv
  Time Series Analysis/LSTM_Bot/data/train_predictions.csv
  Time Series Analysis/LSTM_Bot/results/performance_metrics.txt
  Time Series Analysis/LSTM_Bot/results/price_prediction.png
  Time Series Analysis/LSTM_Bot/results/trade_log.csv
  Time Series Analysis/LSTM_Bot/results/trading_results.png
Labels: level1, gssoc-ext, hacktoberfest-accepted

#504 GoogleNewsScraper.-Extracting news articles from Google News
  web scraping in python/newsscraper/GoogleNewsScraper_with_ml.ipynb
  web scraping in python/newsscraper/README.md
  web scraping in python/newsscraper/data.xlsx
  web scraping in python/newsscraper/data_with_ml.xlsx
Labels: level2, gssoc-ext, hacktoberfest-accepted

#510 Implement Face Detection and Blurring in Real-Time
  Computer Vision/Real-Time-Face Blur/haarcascade_frontalface_default.xml
  Computer Vision/Real-Time-Face Blur/main.py
  Computer Vision/Real-Time-Face Blur/readme.md
  Computer Vision/Real-Time-Face Blur/requirements.txt
  Computer Vision/Real-Time-Face Blur/result.jpeg
Labels: level2, gssoc-ext, hacktoberfest-accepted

#521 Spotify playlist automation
  Generative Models/Spotify Playlist Automation/README.md
  Generative Models/Spotify Playlist Automation/config.py
  Generative Models/Spotify Playlist Automation/requirements.txt
  Generative Models/Spotify Playlist Automation/spotify_discover_weekly.py
Labels: gssoc-ext, hacktoberfest-accepted

#522 Shortest path finder
  Generative Models/Shortest-Path-Finder (GUI)/1. Marked Start and End Point.png
  Generative Models/Shortest-Path-Finder (GUI)/2. Made Obstacles.png
  Generative Models/Shortest-Path-Finder (GUI)/3. Shortest Path marked in Purple by the Algorithm.png
  Generative Models/Shortest-Path-Finder (GUI)/README.md
  Generative Models/Shortest-Path-Finder (GUI)/Shortest Path Finder.py
Labels: level2, gssoc-ext, hacktoberfest-accepted

#525 Customer Churn Prediction using ANN Project
  Neural Networks/CustomerChurnPrediction/CustomerChurnPrediction.ipynb
  Neural Networks/CustomerChurnPrediction/README.md
  Neural Networks/CustomerChurnPrediction/customer_data.csv
Labels: level1, gssoc-ext, hacktoberfest-accepted

#532 Parkinson's Disease Classification added
  Supervised Learning/Parkinson's disease classification/PD_data.csv
  Supervised Learning/Parkinson's disease classification/Parkinson's disease.ipynb
  Supervised Learning/Parkinson's disease classification/README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#533 Added Zomato stock prediction
  Prediction Models/Zomato Stock Prediction/Readme.md
  Prediction Models/Zomato Stock Prediction/zomato-stock-deep-learning.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#511 Added Semantic Segmentation
  Computer Vision/Semantic segmentation of body/README.md
  Computer Vision/Semantic segmentation of body/requirements.txt
  Computer Vision/Semantic segmentation of body/segmentation.py
Labels: level1, gssoc-ext, hacktoberfest-accepted

#539 Fix issue 484 :- Added Segment anything on Images
  Computer Vision/Segment Anything on Images/Segment_Anything_in_images.ipynb
  Computer Vision/Segment Anything on Images/readme.md
Labels: level2, gssoc-ext, hacktoberfest-accepted

#540 feat: Generative Models: Image Retriever Bot
  Generative Models/Image Retriever Bot/ReadMe.md
  Generative Models/Image Retriever Bot/generateimageRAG_llamaindex.ipynb
  Generative Models/Image Retriever Bot/images/cat.jpeg
  Generative Models/Image Retriever Bot/images/rag.png
  Generative Models/Image Retriever Bot/images/software.jpeg
  Generative Models/Image Retriever Bot/images/transformer.png
  Generative Models/Image Retriever Bot/images/webdev.jpeg
Labels: level2, gssoc-ext, hacktoberfest-accepted

#546 Added README.md to Time Series Analysis
  Time Series Analysis/README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#542 SmartDocMate - AI-Powered Interactive Document Assistant
  Generative Models/SmartDocMate AI/README.md
  Generative Models/SmartDocMate AI/app.py
  Generative Models/SmartDocMate AI/groq_inference.py
  Generative Models/SmartDocMate AI/requirements.txt
Labels: level2, gssoc-ext, hacktoberfest-accepted

#548 Style Transfer Algorithm added
  Style Transfer/README.md
  Style Transfer/style_transfer_gan.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#550 Tourist Recommendation System
  Recommendation Systems/tourist_recommendation_system/README.md
  Recommendation Systems/tourist_recommendation_system/Top Indian Places to Visit.csv
  Recommendation Systems/tourist_recommendation_system/Tourist_Recommendation_System.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#541 Implementation of Advanced UNet-VGG16 Model for Lunar Rock Segmentation
  Computer Vision/Rock Segmentation/Readme.md
  Computer Vision/Rock Segmentation/Rock_Segmentation.ipynb
Labels: level2, gssoc-ext, hacktoberfest-accepted

#555 Added Dental Anatomy Detection using YOLO
  Computer Vision/Dental Anatomy Classification/Readme.md
  Computer Vision/Dental Anatomy Classification/dental-yolov9.ipynb
  Computer Vision/Dental Anatomy Classification/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted

#556 POS_Blockchain_Malicious_Node_Detection
  Neural Networks/POS_Blockchain_Malicious_Node_Detection/README.md
  Neural Networks/POS_Blockchain_Malicious_Node_Detection/data/Blockchain101.csv
  Neural Networks/POS_Blockchain_Malicious_Node_Detection/requirements.txt
  Neural Networks/POS_Blockchain_Malicious_Node_Detection/src/__pycache__/model.cpython-310.pyc
  Neural Networks/POS_Blockchain_Malicious_Node_Detection/src/__pycache__/utils.cpython-310.pyc
  Neural Networks/POS_Blockchain_Malicious_Node_Detection/src/main.py
  Neural Networks/POS_Blockchain_Malicious_Node_Detection/src/model.py
  Neural Networks/POS_Blockchain_Malicious_Node_Detection/src/results/figures/lstm_confusion_matrix.png
  Neural Networks/POS_Blockchain_Malicious_Node_Detection/src/results/figures/lstm_pr_curve.png
  Neural Networks/POS_Blockchain_Malicious_Node_Detection/src/results/figures/lstm_roc_curve.png
  Neural Networks/POS_Blockchain_Malicious_Node_Detection/src/results/figures/lstm_training_history.png
  Neural Networks/POS_Blockchain_Malicious_Node_Detection/src/results/metrics/lstm_metrics.txt
  Neural Networks/POS_Blockchain_Malicious_Node_Detection/src/utils.py
Labels: level2, gssoc-ext, hacktoberfest-accepted

#565 Added Message precision detection for SMS
  Supervised Learning/Messege precision detection for sms/SMSSpamCollection.csv
  Supervised Learning/Messege precision detection for sms/SMSSpamDetection.py
Labels: level1, gssoc-ext, hacktoberfest-accepted

#573 Added README.md for House Price Prediction
  Prediction Models/Housing_Price_Prediction/README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#580 Create README.md for Diabetes Prediction app
  Prediction Models/Diabetes-Prediction-app/README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#581 Enhanced Age and Gender Prediction Model with Functional API and VGG16 Backbone
  Computer Vision/Age gender prediction from image/.gitignore
  Computer Vision/Age gender prediction from image/Age_gender.ipynb
  Computer Vision/Age gender prediction from image/README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#570 Text-to-Speech model using Transformers
  Natural Language Processing/Text-to-Speech/README.md
  Natural Language Processing/Text-to-Speech/Text-to-Speech.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#583 Feature request: Cold Email Generator App
  Generative Models/Cold Email generator/.env
  Generative Models/Cold Email generator/README.md
  Generative Models/Cold Email generator/app/app.py
  Generative Models/Cold Email generator/app/requirements.txt
Labels: level1, gssoc-ext, hacktoberfest-accepted

#589 Skin-Cancer-Detection
  Prediction Models/Skin Cancer Detection/Output-1.png
  Prediction Models/Skin Cancer Detection/Output-2.png
  Prediction Models/Skin Cancer Detection/Output-3.png
  Prediction Models/Skin Cancer Detection/Output-4.png
  Prediction Models/Skin Cancer Detection/Output-5.png
  Prediction Models/Skin Cancer Detection/Output-6.png
  Prediction Models/Skin Cancer Detection/readme.md
  Prediction Models/Skin Cancer Detection/requirements.txt
  Prediction Models/Skin Cancer Detection/skin-cancer-detection.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#594 Add files via upload
  Prediction Models/stress_level_detect/model.py
  Prediction Models/stress_level_detect/notebooks/stress_level_detection.ipynb
  Prediction Models/stress_level_detect/predict.py
  Prediction Models/stress_level_detect/saved_models/random_forest_model.joblib
Labels: level1, gssoc-ext, hacktoberfest-accepted

#595 Added model to analyze the physicochemical attributes of wine
  Prediction Models/wine_type/README.md
  Prediction Models/wine_type/test.py
  Prediction Models/wine_type/trained_models/decision_tree_model.pkl
  Prediction Models/wine_type/trained_models/gradient_boosting_model.pkl
  Prediction Models/wine_type/trained_models/knn_model.pkl
  Prediction Models/wine_type/trained_models/logistic_regression_model.pkl
  Prediction Models/wine_type/trained_models/random_forest_model.pkl
  Prediction Models/wine_type/trained_models/svc_model.pkl
  Prediction Models/wine_type/training.py.ipynb
  Prediction Models/wine_type/winequalityN.csv
Labels: level1, gssoc-ext, hacktoberfest-accepted

#600 Contributed Sentiment Analysis App
  Natural Language Processing/Sentiment Analysis Streamlit App/README.md
  Natural Language Processing/Sentiment Analysis Streamlit App/app.png
  Natural Language Processing/Sentiment Analysis Streamlit App/app.py
  Natural Language Processing/Sentiment Analysis Streamlit App/data/sentiment_data.csv
  Natural Language Processing/Sentiment Analysis Streamlit App/requirements.txt
  Natural Language Processing/Sentiment Analysis Streamlit App/sentiment_analysis.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#601 Added the folder of ball tracking
  Computer Vision/Ball Tracking/model.ipynb
  Computer Vision/Ball Tracking/readme.md
  Computer Vision/Ball Tracking/video.mp4
Labels: level1, gssoc-ext, hacktoberfest-accepted

#604 Add files via upload
  Time Series Analysis/Monte_Carlo_Options_Pricing/requirements.txt
  Time Series Analysis/Monte_Carlo_Options_Pricing/results/data/simulation_results.txt
  Time Series Analysis/Monte_Carlo_Options_Pricing/results/plots/price_paths.png
  Time Series Analysis/Monte_Carlo_Options_Pricing/run_simulation.py
  Time Series Analysis/Monte_Carlo_Options_Pricing/src/__pycache__/config.cpython-310.pyc
  Time Series Analysis/Monte_Carlo_Options_Pricing/src/__pycache__/monte_carlo.cpython-310.pyc
  Time Series Analysis/Monte_Carlo_Options_Pricing/src/__pycache__/utils.cpython-310.pyc
  Time Series Analysis/Monte_Carlo_Options_Pricing/src/__pycache__/visualization.cpython-310.pyc
  Time Series Analysis/Monte_Carlo_Options_Pricing/src/config.py
  Time Series Analysis/Monte_Carlo_Options_Pricing/src/monte_carlo.py
  Time Series Analysis/Monte_Carlo_Options_Pricing/src/utils.py
  Time Series Analysis/Monte_Carlo_Options_Pricing/src/visualization.py
Labels: level1, gssoc-ext, hacktoberfest-accepted

#608 Text2SQL (Natural Language to SQL Generation )
  Generative Models/Text2SQL/README.md
  Generative Models/Text2SQL/requirements.txt
  Generative Models/Text2SQL/sql.py
  Generative Models/Text2SQL/tex2sql.ipynb
Labels: level2, gssoc-ext, hacktoberfest-accepted

#610 Feature request: Steel Plate Multi Class Defect Prediction model completed
  Prediction Models/Steel-Plate-Multi-Class-Defect-Prediction/README.md
  Prediction Models/Steel-Plate-Multi-Class-Defect-Prediction/XGB_submission_2.csv
  Prediction Models/Steel-Plate-Multi-Class-Defect-Prediction/playground-series-s4e3/sample_submission.csv
  Prediction Models/Steel-Plate-Multi-Class-Defect-Prediction/playground-series-s4e3/test.csv
  Prediction Models/Steel-Plate-Multi-Class-Defect-Prediction/playground-series-s4e3/train.csv
  Prediction Models/Steel-Plate-Multi-Class-Defect-Prediction/ps-s4-ep3.ipynb
  Prediction Models/Steel-Plate-Multi-Class-Defect-Prediction/steel+plates+faults/Faults.NNA
  Prediction Models/Steel-Plate-Multi-Class-Defect-Prediction/steel+plates+faults/Faults27x7_var
Labels: level1, gssoc-ext, hacktoberfest-accepted

#616 Lung Cancer Risk assesment
  Prediction Models/LungCancerDetection/README.md
  Prediction Models/LungCancerDetection/notebooks/CNNresultsAnalysis.ipynb
  Prediction Models/LungCancerDetection/notebooks/LungCancerDetection.ipynb
  Prediction Models/LungCancerDetection/src/models/cnn_model.py
  Prediction Models/LungCancerDetection/src/models/conv_layer_0.png
  Prediction Models/LungCancerDetection/src/models/conv_layer_1.png
  Prediction Models/LungCancerDetection/src/models/conv_layer_2.png
  Prediction Models/LungCancerDetection/src/models/predict_model.py
  Prediction Models/LungCancerDetection/src/models/train.py
  Prediction Models/LungCancerDetection/src/models/visualize_model.py
  Prediction Models/LungCancerDetection/src/models/weight_conv_layer_0.png
Labels: level2, gssoc-ext, hacktoberfest-accepted

#627 Update languages.json in file
  Generative Models/LLM Copilot Extension for VS Code IDE/languages.json
Labels: level1, gssoc-ext, hacktoberfest-accepted

#628 Frontal Face Generating Model
  Generative Models/Frontal Face Generator/PSP_frontalization_notebook.ipynb
  Generative Models/Frontal Face Generator/Readme.md
  Time Series Analysis/Hotel Demand Forecasting/Hotel Demand Forecasting.ipynb
  Time Series Analysis/Hotel Demand Forecasting/Readme.md
Labels: level2, gssoc-ext, hacktoberfest-accepted

#629 Personalised Workout reccomendation system
  Recommendation Systems/Personalised Workout Recommendation System/README.md
  Recommendation Systems/Personalised Workout Recommendation System/index.html
  Recommendation Systems/Personalised Workout Recommendation System/package-lock.json
  Recommendation Systems/Personalised Workout Recommendation System/package.json
  Recommendation Systems/Personalised Workout Recommendation System/public/vite.svg
  Recommendation Systems/Personalised Workout Recommendation System/src/App.css
  Recommendation Systems/Personalised Workout Recommendation System/src/App.jsx
  Recommendation Systems/Personalised Workout Recommendation System/src/assets/react.svg
  Recommendation Systems/Personalised Workout Recommendation System/src/assets/smartFitLogo.png
  Recommendation Systems/Personalised Workout Recommendation System/src/components/Form.jsx
  Recommendation Systems/Personalised Workout Recommendation System/src/components/LandingHero.jsx
  Recommendation Systems/Personalised Workout Recommendation System/src/components/Navbar.tsx
  Recommendation Systems/Personalised Workout Recommendation System/src/index.css
  Recommendation Systems/Personalised Workout Recommendation System/src/main.jsx
  Recommendation Systems/Personalised Workout Recommendation System/src/pages/Conversation.jsx
  Recommendation Systems/Personalised Workout Recommendation System/src/pages/Home.jsx
  Recommendation Systems/Personalised Workout Recommendation System/src/pages/NoPageFound.jsx
  Recommendation Systems/Personalised Workout Recommendation System/src/pages/Result.jsx
  Recommendation Systems/Personalised Workout Recommendation System/src/redux/store.js
  Recommendation Systems/Personalised Workout Recommendation System/src/redux/workoutApi.js
  Recommendation Systems/Personalised Workout Recommendation System/src/redux/workoutSlice.js
  Recommendation Systems/Personalised Workout Recommendation System/vite.config.js
Labels: level2, gssoc-ext, hacktoberfest-accepted

#633 Created issue-reminder.yml
  .github/workflows/issue-reminder.yml
Labels: level1, gssoc-ext, hacktoberfest-accepted

#635 Hotel Demand EDA and Forecasting using ARIMA and SARIMA Model
  Time Series Analysis/Hotel Demand Forecasting/Readme.md
Labels: gssoc-ext, hacktoberfest-accepted

#641 Feature request: add a space inveder game using computer vision #639
  Computer Vision/Space Invaders/Readme.md
  Computer Vision/Space Invaders/assets/audios/background_music.mp3
  Computer Vision/Space Invaders/assets/fonts/RAVIE.TTF
  Computer Vision/Space Invaders/assets/fonts/comicbd.ttf
  Computer Vision/Space Invaders/assets/images/1920x1080p.jpg
  Computer Vision/Space Invaders/assets/images/800x600p.jpg
  Computer Vision/Space Invaders/assets/images/background.png
  Computer Vision/Space Invaders/assets/images/bullet.png
  Computer Vision/Space Invaders/assets/images/enemy.png
  Computer Vision/Space Invaders/assets/images/enemy2.png
  Computer Vision/Space Invaders/assets/images/enemy3.png
  Computer Vision/Space Invaders/assets/images/enemy4.png
  Computer Vision/Space Invaders/assets/images/space-invaders.png
  Computer Vision/Space Invaders/assets/images/ufo.png
  Computer Vision/Space Invaders/game_HIGH_RES.py
  Computer Vision/Space Invaders/game_LOW_RES.py
  Computer Vision/Space Invaders/requirements.txt
Labels: level2, gssoc-ext, hacktoberfest-accepted

#645 Added chatbot.py file in Chatbot-learn-GenAI using feature
  Generative Models/Chatbot-learn-GenAI/chatbot.py
Labels: level1, gssoc-ext, hacktoberfest-accepted

#646 Added Rick Sanchez Bot created using Transformers
  Natural Language Processing/rick_bot/README.md
  Natural Language Processing/rick_bot/RickAndMortyScripts.csv
  Natural Language Processing/rick_bot/test.py
  Natural Language Processing/rick_bot/training.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#673 sleep disorder analysis added
  Prediction Models/sleep_disorder_predictor/data/dataset.csv
  Prediction Models/sleep_disorder_predictor/model.py
  Prediction Models/sleep_disorder_predictor/notebooks/sleep-disorder.ipynb
  Prediction Models/sleep_disorder_predictor/predict.py
  Prediction Models/sleep_disorder_predictor/readme.md
  Prediction Models/sleep_disorder_predictor/requirements.txt
  Prediction Models/sleep_disorder_predictor/saved_models/Model_Prediction.sav
  Prediction Models/sleep_disorder_predictor/saved_models/preprocessor.sav
Labels: gssoc-ext, hacktoberfest-accepted

#677 Life Expectancy Prediction Added
  Prediction Models/Life Expectancy Prediction/Dataset/Life Expectancy Data.csv
  Prediction Models/Life Expectancy Prediction/life-expectancy-prediction.ipynb
  Prediction Models/Life Expectancy Prediction/readme.md
  Prediction Models/Life Expectancy Prediction/requirements.txt
Labels: level1, gssoc-ext, hacktoberfest-accepted

#682 Gold price prediction added
  Prediction Models/Gold Price Prediction/Gold_Price_Prediction_main.ipynb
  Prediction Models/Gold Price Prediction/README.md
  Prediction Models/Gold Price Prediction/gld_price_data.csv
Labels: level1, gssoc-ext, hacktoberfest-accepted

#683 updated readme with troubleshooting.
  README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#685 Added Data Summarizer using NLP
  Natural Language Processing/Data Summarizer/Requirements/index.html
  Natural Language Processing/Data Summarizer/app.cpython-39.pyc
  Natural Language Processing/Data Summarizer/main.py
  Natural Language Processing/Data Summarizer/requirements.txt
Labels: level1, gssoc-ext, hacktoberfest-accepted

#686 Add Social Network Analysis Project to Unsupervised Learning and Blood Donations Prediction to Prediction Models Module
  Prediction Models/Blood Donations Prediction/Blood Donation Prediction.ipynb
  Prediction Models/Blood Donations Prediction/LICENSE
  Prediction Models/Blood Donations Prediction/README.md
  Prediction Models/Blood Donations Prediction/data/test.csv
  Prediction Models/Blood Donations Prediction/data/train.csv
  Unsupervised Learning/Social Network Analysis/README.md
  Unsupervised Learning/Social Network Analysis/Social Network Analysis.ipynb
  Unsupervised Learning/Social Network Analysis/data/star-wars-network-edges.csv
  Unsupervised Learning/Social Network Analysis/data/star-wars-network-nodes.csv
  Unsupervised Learning/Social Network Analysis/img/hastie_etal-f12-1.png
  Unsupervised Learning/Social Network Analysis/img/net-1-edge.png
  Unsupervised Learning/Social Network Analysis/img/net-1-node.png
  Unsupervised Learning/Social Network Analysis/img/net-1.png
  Unsupervised Learning/Social Network Analysis/img/precision-recall.png
  Unsupervised Learning/Social Network Analysis/img/supervised-learning.png
Labels: level1, gssoc-ext, hacktoberfest-accepted

#687 Add a text-based RAG chatbot
  Generative Models/RAG-Chatbot/ML_Nexus.txt
  Generative Models/RAG-Chatbot/image.png
  Generative Models/RAG-Chatbot/rag_llama.py
  Generative Models/RAG-Chatbot/readme.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#697 smart-phone-analysis
  Prediction Models/smartphone_rate_prediction/README.md
  Prediction Models/smartphone_rate_prediction/dataset.csv
  Prediction Models/smartphone_rate_prediction/main.py
Labels: level1, gssoc-ext, hacktoberfest-accepted
