Repository UppuluriKalyani/ML-Nexus, pull requests merged in 2024-11, with the labels that each got.

#700 Updated the readme file
  README.md
  assets/GSSoC-Ext.png
  assets/hacktoberfest.png
  assets/image
Labels: level1, gssoc-ext, hacktoberfest-accepted

#708 Fixes #704 coffee Bean Classification
  Prediction Models/Coffee_bean_Classification/Readme.md
  Prediction Models/Coffee_bean_Classification/coffee-bean-classification-with-deep-learning.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#711 Feature/portfolio-website
  ml-nexus/.gitignore
  ml-nexus/README.md
  ml-nexus/eslint.config.js
  ml-nexus/index.html
  ml-nexus/package-lock.json
  ml-nexus/package.json
  ml-nexus/postcss.config.js
  ml-nexus/public/vite.svg
  ml-nexus/src/App.css
  ml-nexus/src/App.jsx
  ml-nexus/src/assets/react.svg
  ml-nexus/src/components/Btn.jsx
  ml-nexus/src/components/Card.jsx
  ml-nexus/src/components/ContributeSection.jsx
  ml-nexus/src/components/Contributors.jsx
  ml-nexus/src/components/Footer.jsx
  ml-nexus/src/components/Hero.jsx
  ml-nexus/src/components/Home.jsx
  ml-nexus/src/components/Nav.jsx
  ml-nexus/src/components/Projects.jsx
  ml-nexus/src/components/Statistics.jsx
  ml-nexus/src/components/Stats.jsx
  ml-nexus/src/index.css
  ml-nexus/src/main.jsx
  ml-nexus/src/utils/Context.jsx
  ml-nexus/src/utils/axios.jsx
  ml-nexus/src/utils/routing.jsx
  ml-nexus/tailwind.config.js
  ml-nexus/vite.config.js
Labels: gssoc-ext, hacktoberfest-accepted

#710 Create SECURITY.md
  Style Transfer/SECURITY.md
Labels: gssoc-ext, hacktoberfest-accepted

#715 Deployment ready and bug fixes
  ml-nexus/src/utils/Context.jsx
Labels: gssoc-ext, hacktoberfest-accepted

#716 Added image colorization
  Neural Networks/Image Colorization/colorization_project/README.md
Labels: level2, gssoc-ext, hacktoberfest-accepted

#718 added implementations
  Computer Vision/image-to-text model/implementations.md
Labels: gssoc-ext, hacktoberfest-accepted

#723 Fixes #717 Taxi Fare prediction
  Prediction Models/Taxi-Fare_Prediction/README.md
  Prediction Models/Taxi-Fare_Prediction/taxi-fare-prediction-with-keras-deep-learning.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#726 Crop_Pred_model_added
  Prediction Models/Crop_Yeild_Prediction/CropYield-Prediction.ipynb
  Prediction Models/Crop_Yeild_Prediction/README.md
  Prediction Models/Crop_Yeild_Prediction/app.py
  Prediction Models/Crop_Yeild_Prediction/dtr.pkl
  Prediction Models/Crop_Yeild_Prediction/preprocessor.pkl
  Prediction Models/Crop_Yeild_Prediction/templates/index.html
  Prediction Models/Crop_Yeild_Prediction/yield_df.csv
Labels: level1, gssoc-ext, hacktoberfest-accepted

#729 modified index.html file
  Prediction Models/Crop_Yeild_Prediction/templates/index.html
Labels: gssoc-ext, hacktoberfest-accepted

#731 Spotify playlist Automation
  Recommendation Systems/Spotify Playlist Automation/README.md
  Recommendation Systems/Spotify Playlist Automation/config.py
  Recommendation Systems/Spotify Playlist Automation/requirements.txt
  Recommendation Systems/Spotify Playlist Automation/spotify_discover_weekly.py
Labels: level2, gssoc-ext, hacktoberfest-accepted

#730 Added an new project called "Turn Images into Story with AI"
  Generative Models/Turn Images Into Story with AI/README.md
  Generative Models/Turn Images Into Story with AI/app.py
  Generative Models/Turn Images Into Story with AI/requirments.txt
Labels: level2, gssoc-ext, hacktoberfest-accepted

#732 Fixes #725 Visual Chessboard Analysis: CNN-based FEN Code Generation
  Prediction Models/Chess_Prediction/Readme.md
  Prediction Models/Chess_Prediction/chess-positions-fen-prediction-eda-cnn-model.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#738 Struct
  Project Structure Map.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#741 Added a new project called "Object Detector"
  Generative Models/Object Detector/README.md
  Generative Models/Object Detector/app.py
  Generative Models/Object Detector/requirements.txt
  Generative Models/Turn Images Into Story with AI/README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#752 Feature Added: Diet Recommendation System with Machine Learning for Calorie and Dietary Type Predictions
  Recommendation Systems/Personalised Diet Recommendation System/LICENSE.md
  Recommendation Systems/Personalised Diet Recommendation System/README.md
  Recommendation Systems/Personalised Diet Recommendation System/diet_recommendation_system.ipynb
  Recommendation Systems/Personalised Diet Recommendation System/food.csv
  Recommendation Systems/Personalised Diet Recommendation System/food1.csv
  Recommendation Systems/Personalised Diet Recommendation System/model.py
  Recommendation Systems/Personalised Diet Recommendation System/output.png
  Recommendation Systems/Personalised Diet Recommendation System/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted

#756 Fixes #754 Air quality prediction
  Prediction Models/Air_Quality_prediction/Readme.md
  Prediction Models/Air_Quality_prediction/air-quality-prediction-model-by-lstm.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#757 Fixes #755 Kidney Stone Prediction
  Prediction Models/Kidney_stone_prediction/kidney-stone-eda-prediction-7-model-2-nn.ipynb
  Prediction Models/Kidney_stone_prediction/readme.md
Labels: gssoc-ext, hacktoberfest-accepted

#760 Added a new project called "Text Summarizer"
  Generative Models/Text Summarizer/README.md
  Generative Models/Text Summarizer/app.py
  Generative Models/Text Summarizer/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted

#766 Added spacing between hot topic cards and hover effects
  ml-nexus/src/components/Card.jsx
  ml-nexus/src/components/Hero.jsx
Labels: gssoc-ext, hacktoberfest-accepted

#765 Fixes Mushroom Classification
  Prediction Models/Mushroom_Classification/Readme.md
  Prediction Models/Mushroom_Classification/mushroom-classification-notebook.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#764 Fixes #762 Mobile Price Prediction
  Prediction Models/Mobile_price_prediction/Readme.md
  Prediction Models/Mobile_price_prediction/mobile-price-prediction-classification-models.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#773 Fixes #770 Advertisement Budget Prediction
  Prediction Models/Advertisement_Budget/Readme.md
  Prediction Models/Advertisement_Budget/advertisement-budget-prediction-top-ml-models.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#774 Fixes #772 Playstore Rating Prediction
  Prediction Models/Playstore_Rating_Prediction/Readme.md
  Prediction Models/Playstore_Rating_Prediction/playstore-ratings-prediction-regression-model.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#777 Fixes #776 MMA Fight Prediction
  Prediction Models/MMA_Fight_prediction/Readme.md
  Prediction Models/MMA_Fight_prediction/mma-ml-model-fight-predictions-ufc-259.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#781 Added about, contact pages with Routing with mobile responsiveness
  ml-nexus/public/kp.jpg
  ml-nexus/src/App.jsx
  ml-nexus/src/components/About.jsx
  ml-nexus/src/components/Contact.jsx
  ml-nexus/src/components/Footer.jsx
  ml-nexus/src/components/Home.jsx
  ml-nexus/src/components/Nav.jsx
  ml-nexus/src/utils/routing.jsx
Labels: level2, gssoc-ext, hacktoberfest-accepted

#780 Fixes #779 Car Mileage Prediction model
  Prediction Models/Car_Mileage_Prediction/Readme.md
  Prediction Models/Car_Mileage_Prediction/car-mileage-prediction-model.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#783 Improved UI of project cards + mobile responsiveness
  ml-nexus/src/components/Projects.jsx
Labels: gssoc-ext, hacktoberfest-accepted

#787 Fixes #785 Dementia Prediction Model
  Prediction Models/Dementia_Prediction/Readme.md
  Prediction Models/Dementia_Prediction/dementia-prediction-using-different-ml-model.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#788 Fixes #786 Crab_Age_Prediction
  Prediction Models/Crab_Age_Prediction/Readme.md
  Prediction Models/Crab_Age_Prediction/crab-age-predictions-eda-f-e-modeling-10th.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#791 Interactive Data Visualizations tool
  tools/app.py
  tools/requirements.txt
  tools/static/style.css
  tools/templates/index.html
  tools/visualizations/plots.py
Labels: level2, gssoc-ext, hacktoberfest-accepted

#794 Implement a Gesture-Based Keyboard Interface Using Webcam #30
  Computer Vision/Gesture-Based Keyboard Interface Using Webcam/README.md
  Computer Vision/Gesture-Based Keyboard Interface Using Webcam/main.py
  Computer Vision/Gesture-Based Keyboard Interface Using Webcam/output/Screenshot 2024-11-06 164915.png
  Computer Vision/Gesture-Based Keyboard Interface Using Webcam/output/desktop.ini
  Computer Vision/Gesture-Based Keyboard Interface Using Webcam/output/typed_text_20241106_160434.txt
  Computer Vision/Gesture-Based Keyboard Interface Using Webcam/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted

#804 Breast cancer classification readme.md and .ipynb file update
  Neural Networks/Breast cancer classification/Breast_Cancer_Classification_using_Neural_Network.ipynb
  Neural Networks/Breast cancer classification/README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#801 Fixes #800 Deposit Prediction in Banks
  Prediction Models/Deposit_Prediction/Readme.md
  Prediction Models/Deposit_Prediction/bank-deposit-prediction-different-models-91.ipynb
  Prediction Models/Liver_cirrhosis_prediction/liver-cirrhosis-prediction-eda-models.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#797 Fixes #796 Avocado Price Prediction with Machine Learning Models
  Prediction Models/Avocado_Prediction/Readme.md
  Prediction Models/Avocado_Prediction/avocados-predictions-with-ml-models-keras-ann.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#805 Feature request: Image Autoregressive Modeling #768
  Generative Models/ Image Autoregressive Modeling/config/stage1/dino_base.yaml
  Generative Models/ Image Autoregressive Modeling/config/stage1/dino_base_classcond.yaml
  Generative Models/ Image Autoregressive Modeling/config/stage1/dino_base_linearprobe_sgd.yaml
  Generative Models/ Image Autoregressive Modeling/config/stage2/dino_base.yaml
  Generative Models/ Image Autoregressive Modeling/config/stage2/dino_base_nar.yaml
  Generative Models/ Image Autoregressive Modeling/config/stage2/vq_base.yaml
  Generative Models/ Image Autoregressive Modeling/config/vqgan/vqgan.yaml
  Generative Models/ Image Autoregressive Modeling/fairseq_user/__init__.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/criterion.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/dataset.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/distributed.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/eval_fid.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/image_generation_stage1/__init__.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/image_generation_stage1/generator.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/image_generation_stage1/model.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/image_generation_stage1/model_linearprobe.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/image_generation_stage1/sgd_hydra.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/image_generation_stage1/task.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/image_generation_stage2/__init__.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/image_generation_stage2/generator.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/image_generation_stage2/model.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/image_generation_stage2/model_nar.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/image_generation_stage2/model_vq.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/image_generation_stage2/taming/models/vqgan.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/image_generation_stage2/taming/modules/diffusionmodules/model.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/image_generation_stage2/taming/modules/util.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/image_generation_stage2/taming/modules/vqvae/quantize.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/image_generation_stage2/taming/util.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/image_generation_stage2/task.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/pretrained_enc/__init__.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/pretrained_enc/dino/__init__.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/pretrained_enc/dino/vits.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/pretrained_enc/ibot/__init__.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/pretrained_enc/ibot/vits.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/pretrained_enc/mae/__init__.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/pretrained_enc/mae/vits.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/pretrained_enc/moco_v3/__init__.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/pretrained_enc/moco_v3/vits.py
  Generative Models/ Image Autoregressive Modeling/fairseq_user/pretrained_enc/models_pretrained_enc.py
  Generative Models/ Image Autoregressive Modeling/prepare_imgnet_val.py
  Generative Models/ Image Autoregressive Modeling/preprocess/cluster_kmeans.py
  Generative Models/ Image Autoregressive Modeling/preprocess/data_handler.py
  Generative Models/ Image Autoregressive Modeling/preprocess/dinov2_encoder.py
  Generative Models/ Image Autoregressive Modeling/preprocess/distributed.py
  Generative Models/ Image Autoregressive Modeling/preprocess/dump_features.py
  Generative Models/ Image Autoregressive Modeling/preprocess/run.sh
  Generative Models/ Image Autoregressive Modeling/readme.md
  Generative Models/ Image Autoregressive Modeling/scripts/infer_stage1_ar.sh
  Generative Models/ Image Autoregressive Modeling/scripts/infer_stage1_ar_classcond.sh
  Generative Models/ Image Autoregressive Modeling/scripts/infer_stage2_ar.sh
  Generative Models/ Image Autoregressive Modeling/scripts/infer_stage2_nar.sh
  Generative Models/ Image Autoregressive Modeling/scripts/infer_stage_vq.sh
  Generative Models/ Image Autoregressive Modeling/scripts/train_stage1_ar.sh
  Generative Models/ Image Autoregressive Modeling/scripts/train_stage1_linearprobe.sh
  Generative Models/ Image Autoregressive Modeling/scripts/train_stage2_ar.sh
  Generative Models/ Image Autoregressive Modeling/scripts/train_stage2_nar.sh
  Generative Models/ Image Autoregressive Modeling/scripts/train_stage_vq.sh
  Generative Models/ Image Autoregressive Modeling/unified_tsv.py
Labels: level2, gssoc-ext, hacktoberfest-accepted

#812 Added pagination in web scraping code
  web scraping in python/quotes.toscrape.com/scrap.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#814 Added waste management solution using advanced reinforcement learning techniques
  Reinforcement Learning/Waste Management through advanced RL techniques/README.md
  Reinforcement Learning/Waste Management through advanced RL techniques/Visualizing_Epsilon_Decay_and_Scores_in_Reinforcement_Learning.ipynb
  Reinforcement Learning/Waste Management through advanced RL techniques/Waste_Management_through_RL (2).ipynb
  Reinforcement Learning/Waste Management through advanced RL techniques/jsconfig.json
  Reinforcement Learning/Waste Management through advanced RL techniques/requirements.txt
  Reinforcement Learning/Waste Management through advanced RL techniques/waste mngmt
  Reinforcement Learning/Waste Management through advanced RL techniques/waste-management.py
Labels: level2, gssoc-ext, hacktoberfest-accepted

#817 Fixes #815 Electron Energy Flux Prediction
  Prediction Models/Electron_energy_Prediction/Readme.md
  Prediction Models/Electron_energy_Prediction/electron-energy-flux-prediction-part-2-modeling.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#818 Fixdes #816 Hepatitis Prediction Model
  Prediction Models/Hepatitis Prediction/Readme.md
  Prediction Models/Hepatitis Prediction/hepatitis-prediction-model-randomforest.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#820 Fixes 819 Horse Survival Prediction
  Prediction Models/Horse_Survival_Prediction/Readme.md
  Prediction Models/Horse_Survival_Prediction/horse-survival-prediction-top-ml-models.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#821 Added language percent in stats and fix footer links
  ml-nexus/src/components/Footer.jsx
  ml-nexus/src/components/Statistics.jsx
Labels: level1, gssoc-ext, hacktoberfest-accepted

#823 Added Project: Image Classification Using CNN (CIFAR-10 Dataset) under the Neural Networks Folder
  Neural Networks/Image Classification Using CNN (CIFAR-10)/Image_Classification_Using_CNN_(CIFAR_10).ipynb
  Neural Networks/Image Classification Using CNN (CIFAR-10)/Model_Prediction.sav
  Neural Networks/Image Classification Using CNN (CIFAR-10)/README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#825 Hotel Reservation Cancellation Prediction
  Prediction Models/Hotel_reservation_cancel_prediction/Readme.md
  Prediction Models/Hotel_reservation_cancel_prediction/hotel-reservations-predictions-models.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#826 Added github profile URL and count of contributions
  ml-nexus/src/components/Contributors.jsx
Labels: gssoc-ext, hacktoberfest-accepted

#827 Added logo and favicon
  ml-nexus/index.html
  ml-nexus/public/mlnexus.jpg
  ml-nexus/src/components/Nav.jsx
Labels: gssoc-ext, hacktoberfest-accepted

#828 Fix footer links
  ml-nexus/src/components/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted

#831 Data Scientist Salary Prediction
  Prediction Models/Data_science_salary_prediction/Readme.md
  Prediction Models/Data_science_salary_prediction/data-scientist-salary-prediction-model.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#832 Facial Expression Detection Model using CNN
  Prediction Models/Facial_expression_prediction/Readme.md
  Prediction Models/Facial_expression_prediction/facial-expression-detection-cnn.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#841 Creating an 3D voxel design generation tool using advanced deep learning models -GANs
  Neural Networks/Generating 3D Voxel designs using GANs/3D Voxels Generation tool
  Neural Networks/Generating 3D Voxel designs using GANs/3D_Gen.ipynb
  Neural Networks/Generating 3D Voxel designs using GANs/README.md
  Neural Networks/Generating 3D Voxel designs using GANs/requirements.py
  Neural Networks/Generating 3D Voxel designs using GANs/src/outputs/img
  Neural Networks/Generating 3D Voxel designs using GANs/src/outputs/vox1.png
  Neural Networks/Generating 3D Voxel designs using GANs/src/outputs/vox2.png
  Neural Networks/Generating 3D Voxel designs using GANs/src/outputs/vox3.png
  Neural Networks/Generating 3D Voxel designs using GANs/src/outputs/vox4.png
  Neural Networks/Generating 3D Voxel designs using GANs/src/outputs/vox5.png
Labels: level2, gssoc-ext, hacktoberfest-accepted

#839 Add SLAM [Simultaneous Localization and Mapping]
  Robotics Using AI/Basic SLAM/Readme.md
  Robotics Using AI/Basic SLAM/slam.py
Labels: gssoc-ext, hacktoberfest-accepted

#842 Added quantum circuit probability predictor
  Prediction Models/Quantum Circuit Probability prediction using advanced Machine Learning techniques/ML Quantum Prediction tool
  Prediction Models/Quantum Circuit Probability prediction using advanced Machine Learning techniques/Quantum_model.ipynb
  Prediction Models/Quantum Circuit Probability prediction using advanced Machine Learning techniques/README.md
  Prediction Models/Quantum Circuit Probability prediction using advanced Machine Learning techniques/gitignore.txt
  Prediction Models/Quantum Circuit Probability prediction using advanced Machine Learning techniques/requirements.py
  Prediction Models/Quantum Circuit Probability prediction using advanced Machine Learning techniques/src/Model Output/Images_output
  Prediction Models/Quantum Circuit Probability prediction using advanced Machine Learning techniques/src/Model Output/qpm-1.png
  Prediction Models/Quantum Circuit Probability prediction using advanced Machine Learning techniques/src/Model Output/qpm_2.png
Labels: gssoc-ext, hacktoberfest-accepted

#844 Story generation tool using deep learning models- Hugging Face Transformer architecture model
  Generative Models/Customized Story Generation Tool using Deep Learning Tools- Transformer Architecture model/README.md
  Generative Models/Customized Story Generation Tool using Deep Learning Tools- Transformer Architecture model/Stories.txt
  Generative Models/Customized Story Generation Tool using Deep Learning Tools- Transformer Architecture model/Story_Generation_Model.ipynb
  Generative Models/Customized Story Generation Tool using Deep Learning Tools- Transformer Architecture model/app.py
  Generative Models/Customized Story Generation Tool using Deep Learning Tools- Transformer Architecture model/requirements.txt
  Generative Models/Customized Story Generation Tool using Deep Learning Tools- Transformer Architecture model/src/output/imgs-output
  Generative Models/Customized Story Generation Tool using Deep Learning Tools- Transformer Architecture model/src/output/story-gen2.png
  Generative Models/Customized Story Generation Tool using Deep Learning Tools- Transformer Architecture model/story-gen
Labels: gssoc-ext, hacktoberfest-accepted

#845 Added object detection using coco dataset with the help of advanced yolo v5 model
  Computer Vision/Object detection using COCO dataset with YOLO_v5 advanced model/Object Detection with COCO_dataset_using YOLO.ipynb
  Computer Vision/Object detection using COCO dataset with YOLO_v5 advanced model/README.md
  Computer Vision/Object detection using COCO dataset with YOLO_v5 advanced model/coco_img_YOLO_model
  Computer Vision/Object detection using COCO dataset with YOLO_v5 advanced model/gitignore.txt
  Computer Vision/Object detection using COCO dataset with YOLO_v5 advanced model/obj-det-output.png
  Computer Vision/Object detection using COCO dataset with YOLO_v5 advanced model/requirements.txt
Labels: level1, gssoc-ext, hacktoberfest-accepted

#846 Added advanced mistral llm chatbot
  Generative Models/Advanced Mistral 7B LLM Chatbot/Flask/templates/app.py
  Generative Models/Advanced Mistral 7B LLM Chatbot/Flask/templates/chat.html
  Generative Models/Advanced Mistral 7B LLM Chatbot/Flask/templates/chat.py
  Generative Models/Advanced Mistral 7B LLM Chatbot/Flask/templates/config.py
  Generative Models/Advanced Mistral 7B LLM Chatbot/Flask/templates/temp_files_chat
  Generative Models/Advanced Mistral 7B LLM Chatbot/Flask/templates/test.csv
  Generative Models/Advanced Mistral 7B LLM Chatbot/Mistral_Chatbot.ipynb
  Generative Models/Advanced Mistral 7B LLM Chatbot/README.md
  Generative Models/Advanced Mistral 7B LLM Chatbot/chatbot temp
Labels: level2, gssoc-ext, hacktoberfest-accepted

#857 Updated README.md
  README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#850 Network Security Prediction Models
  Prediction Models/Network_security_prediction/Readme.md
  Prediction Models/Network_security_prediction/network-security-prediction-models.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#851 World Cup Prediction with Deep Learning
  Prediction Models/World_cup_Prediction/Readme.md
  Prediction Models/World_cup_Prediction/world-cup-prediction-with-80-accuracy-in-dl-model.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#855 College Placement Prediction Model
  Prediction Models/College_placement_prediction/Readme.md
  Prediction Models/College_placement_prediction/collegeplacement-predictions-using-multiple-models.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#859 Feature request: Add Anomaly Detection Project
  Anomaly Detection Project/Anomaly_Detection_Project.ipynb
  Anomaly Detection Project/anomalies_report.py
  Anomaly Detection Project/data_preprocessing.py
  Anomaly Detection Project/eda_visualizations.py
  Anomaly Detection Project/isolation_forest_anomaly_detection.py
  Anomaly Detection Project/kmeans_anomaly_detection.py
  Anomaly Detection Project/model_evaluation.py
  Anomaly Detection Project/readme.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#865 Star Classification System - Fixes 861
  Prediction Models/Stars_Classification_Model/Readme.md
  Prediction Models/Stars_Classification_Model/stars-classification.ipynb
Labels: level1, gssoc-ext, hacktoberfest-accepted

#866 Classification of Waste using CNN
  Prediction Models/Classification of Waste using CNN/Readme.md
  Prediction Models/Classification of Waste using CNN/waste-classification-with-cnn.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#867 Potato Disease Classification with CNN
  Prediction Models/Potato_disease_classification/Readme.md
  Prediction Models/Potato_disease_classification/potato-disease-classification-model.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#868 Playtime Classification with Logistic Regression
  Prediction Models/Playtime_prediction/Readme.md
  Prediction Models/Playtime_prediction/playtime-classification-with-logit-model.ipynb
Labels: gssoc-ext, hacktoberfest-accepted

#871 Feature request: transformer-based model for atomistic graph data #806
  Transfer Learning/Atomistic graph data/config.json
  Transfer Learning/Atomistic graph data/configuration_atomformer.py
  Transfer Learning/Atomistic graph data/model.py
  Transfer Learning/Atomistic graph data/modeling_atomformer.py
  Transfer Learning/Atomistic graph data/readme.md
Labels: ml-nexus

#878 Text extractor
  Computer Vision/Text_Extractor/EasyOCR/EasyOCR_output_pdf.pdf
  Computer Vision/Text_Extractor/EasyOCR/EasyOCR_output_text.txt
  Computer Vision/Text_Extractor/EasyOCR/Easy_OCR_code.ipynb
  Computer Vision/Text_Extractor/EasyOCR/easyOCR_output.png
  Computer Vision/Text_Extractor/EasyOCR/testimg_easyOCR.jfif
  Computer Vision/Text_Extractor/Tesseract/Tesseract_output_pdf.pdf
  Computer Vision/Text_Extractor/Tesseract/Tesseract_output_text.txt
  Computer Vision/Text_Extractor/Tesseract/Test_img_tessseract.png
  Computer Vision/Text_Extractor/Tesseract/pyTesseract_code.ipynb
  Computer Vision/Text_Extractor/Tesseract/tesseract_output.png
  Computer Vision/Text_Extractor/readme.md
Labels: level2, gssoc-ext, hacktoberfest-accepted, ml-nexus

#875 Fruit Classification using PCA and Various Classifiers
  Prediction Models/Friut_Classification_model/Readme.md
  Prediction Models/Friut_Classification_model/fruit-classification-pca-svm-knn-decision-tree.ipynb
Labels: ml-nexus

#877 Tomato Leaf Disease Classification
  Prediction Models/Tomato_Leaf_Disease/Readme.md
  Prediction Models/Tomato_Leaf_Disease/tomato-leaf-disease-94-accuracy.ipynb
Labels: gssoc-ext, hacktoberfest-accepted, ml-nexus

#876 Chronic Kidney Disease Prediction Model
  Prediction Models/Chronic_Kidney_Disease_prediction/Readme.md
  Prediction Models/Chronic_Kidney_Disease_prediction/chronic-kidney-disease-prediction-98-accuracy.ipynb
Labels: ml-nexus
